platform:ios,'8.0'
target 'linjinsuo' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'YYKit'
pod 'MJExtension'
pod 'UMengUShare/Social/ReducedWeChat'
pod 'UMengUShare/Social/ReducedQQ'
pod 'UMengUShare/Social/ReducedSina'
pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
pod 'WebViewJavascriptBridge'
pod ‘IQKeyboardManager’
pod 'WMPageController'
pod 'Bugly'

pod 'ReactiveObjC'

pod 'JHNoDataEmptyView'


end

